export enum EControlTypes {
  pkey = 'PRIMARY-KEY',
  input = 'INPUT',
  textArea = 'TEXT-AREA',
  dropdown = 'DROPDOWN',
  date = 'DATE',
  time = 'TIME',
  checkbox = 'CHECKBOX',
  upload = 'UPLOAD',
  autocomplete = 'AUTOCOMPLETE',
  multiple = 'MULTIPLE-AUTOCOMPLETE',
  array = 'ARRAY',
  form = 'FORM',
  label = 'LABEL',
  default = 'DEFAULT',
}
