export enum EControlTypes {
  pkey = 'PRIMARY-KEY',
  input = 'INPUT',
  textArea = 'TEXT-AREA',
  dropdown = 'DROPDOWN',
  date = 'DATE',
  time = 'TIME',
  checkbox = 'CHECKBOX',
  file = 'FILE',
  autocomplete = 'AUTOCOMPLETE',
  multiple = 'MULTIPLE-AUTOCOMPLETE',
  array = 'ARRAY',
  form = 'FORM',
  readOnly = 'READONLY',
  default = 'default',
  phone = 'phone',
}
